### ISSUE TITLE
能否给class，property都加上tableAttribute和ColumnAttribute，包括KeyAttribute

### ISSUE THREAD

**Issue by a157147899** [WeihanLi/DbTool#10]
能否给class，property都加上tableAttribute和ColumnAttribute，包括KeyAttribute，这样生成出来的Model，应该场景更广泛，也便于扩展

**Comment by WeihanLi** [comment]
可以的

> 后面也可以自己实现一个 `IModelCodeGenerator` ，然后将 dll 放在执行目录下的 plugins 目录下，启动时会自动扫描 plugins 目录并自动注册相应的服务，目前还没 nuget 包，需要后面发布一个 `DbTool.Core` 的 nuget 包
