### ISSUE TITLE
生成规则“表名以 tab或 tab_或 tbl或 tbl_”自动替换问题

### ISSUE THREAD

**Issue by cdzhoubin** [WeihanLi/DbTool#12]
在有些场景下，不需要自动替换表名，如：
默认使用旧生成方式：
Scaffold-DbContext "Server=***;User Id=***;Password=***;Database=***;Persist Security Info=True;" Microsoft.EntityFrameworkCore.SqlServer -o Models -f

期望增加配置控制生成时，是否进行“表名以 tab或 tab_或 tbl或 tbl_”替换

**Comment by WeihanLi** [comment]
好的，感谢反馈，下个版本增加配置

**Comment by WeihanLi** [comment]
1.2.0 版本中增加了可选配置
![image](https://user-images.githubusercontent.com/7604648/75155400-f2beac00-574a-11ea-8755-3a33eb692ff7.png)
