### ISSUE TITLE
DbTool.Core 源码

### ISSUE THREAD

**Issue by likethis** [WeihanLi/DbTool#16]
table.Columns = await _dbHelper.GetColumnsInfoAsync(table.TableName);

关键字 'IS' 附近有语法错误。

**Comment by WeihanLi** [comment]
测试的没有问题，你是用的 SqlServer 连接的 MySql 吗？默认数据库类型是 SqlServer，可以在设置里修改数据库类型，下个版本在连接字符串后面增加一个数据库类型的选择

![image](https://user-images.githubusercontent.com/7604648/77744157-2cd5e300-7054-11ea-9804-3a5251d81370.png)
