### ISSUE TITLE
关键字 'IS' 附近有语法错误。'm' 附近有语法错误。 

### ISSUE THREAD

**Issue by nodyang** [WeihanLi/DbTool#24]
System.Data.SqlClient.SqlException (0x80131904): 关键字 'IS' 附近有语法错误。'm' 附近有语法错误。 
![image](https://user-images.githubusercontent.com/3090191/137667710-0ef117af-cbf3-4d2c-8dce-a65ca5abcc68.png)

**Comment by WeihanLi** [comment]
有具体的重现操作步骤吗？从异常信息看上去是 SqlServer 的包抛出来的异常，但是上面的截图的 CREATE TABLE 语句是 `MySql` 系的语法
