### ISSUE TITLE
导出C# Code 报错

### ISSUE THREAD

**Issue by chenqian2008** [WeihanLi/DbTool#27]
![360截图16751025335442](https://user-images.githubusercontent.com/39323100/162346002-b3dabd88-9d09-477d-8d5d-2bb58c0393ee.png)
报以上错误，是在DbTool.Core 里面报的，请问能提供 DbTool.Core工程的源码吗？

**Comment by WeihanLi** [comment]
可以试一下 DbTool 2.0.0 欢迎有问题反馈，感谢感谢

**Comment by WeihanLi** [comment]
先 close 了，有问题的话再开，感谢反馈
