### ISSUE TITLE
DBFirst如果不挨个点一下表，生成出来的model就是空的

### ISSUE THREAD

**Issue by zbzczmeng** [WeihanLi/DbTool#28]

**Comment by WeihanLi** [comment]
生成出来的 model 是指导出的代码是吗？
是怎么操作的？我一般是先选择要导出的表，然后再导出的

**Comment by zbzczmeng** [comment]
> 

就是连接好了数据库之后，左侧会显示出来所有的表，直接点击全选点击导出，然后导出的cs文件里只有一个基础的空类，没有内容
`namespace Models;

public class BaseAppendProperty
{
}`

**Comment by zbzczmeng** [comment]
> 生成出来的 model 是指导出的代码是吗？ 是怎么操作的？我一般是先选择要导出的表，然后再导出的

就是连接好了数据库之后，左侧会显示出来所有的表，直接点击全选点击导出，然后导出的cs文件里只有一个基础的空类，没有内容
`namespace Models;

public class BaseAppendProperty
{
}`

**Comment by WeihanLi** [comment]
好的，我试一下啊

**Comment by WeihanLi** [comment]
发布了一个新的版本 https://github.com/WeihanLi/DbTool/releases/tag/2.1.0 ，可以试一下，我自己测得应该没问题了，感谢反馈

**Comment by zbzczmeng** [comment]
> 发布了一个新的版本 https://github.com/WeihanLi/DbTool/releases/tag/2.1.0 ，可以试一下，我自己测得应该没问题了，感谢反馈

嗯呢，没问题了。手动鼓掌

**Comment by WeihanLi** [comment]
好的，谢谢，issue close 了哈
