### ISSUE TITLE
System.ArgumentNullExcption

### ISSUE THREAD

**Issue by TonyWang972** [WeihanLi/DbTool#32]
execl如下：
![image](https://user-images.githubusercontent.com/55622087/229696844-7ef1dad4-c065-4bd3-b5b4-31f5caa0157b.png)
报错如下：
![image](https://user-images.githubusercontent.com/55622087/229696818-ddc23a96-913a-4a18-9118-f60e16943d76.png)

**Comment by WeihanLi** [comment]
可以帮忙提供一个能够复现问题的 excel 吗

**Comment by WeihanLi** [comment]
没有版本信息以及可以复现问题的 excel，先 close，需要的话可以再打开
