### ISSUE TITLE
我本地build不过

### ISSUE THREAD

**Issue by tww19861004** [WeihanLi/DbTool#4]
怎么弄？

**Comment by WeihanLi** [comment]
哪个分支的代码？

**Comment by WeihanLi** [comment]
wfdev分支的代码用vs可以编译通过，但是直接用命令 `dotnet build`会报错，错误信息如下


> C:\Users\liweihan.TUHU\.nuget\packages\microsoft.codedom.providers.dotnetcompilerplatform\2.0.0\build\net45\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props(31,5): error : MSB4801: 任务工厂“CodeTaskFactory”在 MSBuild 的 .NET Core 版本上不受支持。 [D:\Document\projects\ProjectsSource\DbTool\src\DbTool\DbTool.csproj]
C:\Users\liweihan.TUHU\.nuget\packages\microsoft.codedom.providers.dotnetcompilerplatform\2.0.0\build\net45\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props(31,5): error MSB4175: 未能从程序集“C:\Program Files\dotnet\sdk\2.1.301\Microsoft.Build.Tasks.Core.dll”加载任务工厂“CodeTaskFactory”。任务工厂必须对 "TaskType" 属性返回一个值。 [D:\Document\projects\ProjectsSource\DbTool\src\DbTool\DbTool.csproj]

详见 <https://github.com/aspnet/RoslynCodeDomProvider/issues/56>

**Comment by WeihanLi** [comment]
现在使用 `Microsoft.CodeAnalysis.CSharp` 代替 CodeDom，没有编译问题了
