### ISSUE TITLE
请问什么时候支持mysql？

### ISSUE THREAD

**Issue by geekyouth** [WeihanLi/DbTool#5]

**Comment by WeihanLi** [comment]
现在支持 MySql，你可以下载最新的 Release，解压之后会有一个 `DbTool.exe.config` 的配置文件，你可以修改 DbType 为 `MySql`，默认是 SqlServer

![image](https://user-images.githubusercontent.com/7604648/58869779-7afaae00-86f1-11e9-8124-c4d16411fb4a.png)

如果遇到什么问题，欢迎 issue

**Comment by WeihanLi** [comment]
新发布的 1.0.6 版本，新增加一个 UI 界面可以直接修改数据库类型以及默认的链接字符串

![Setting Page](https://user-images.githubusercontent.com/7604648/59999201-ff5aa400-9693-11e9-85c0-252d56dcbc95.png)
