### ISSUE TITLE
1.0.5 release 文件存在问题

### ISSUE THREAD

**Issue by davidsmithgf** [WeihanLi/DbTool#6]
1.0.5 release 文件存在问题，点击连接后就报错。
连接数据库失败，找不到方法："System.Collections.Generic.IEnumerable`1<!!0>WeihanLi.Extensions.DataExtension.Select(System.Data.Common.DbConnections, System.String, System.Object)"。

下载最新源代码，编译后运行，无此错误。

**Comment by WeihanLi** [comment]
后面更新的主要是 `CodeFirst`，这里没测试，感谢反馈

**Comment by WeihanLi** [comment]
@davidsmithgf 新发布了一个 1.0.6，解决了这个问题，并且新增加了一个界面可以修改默认数据库连接字符串配置以及默认的数据库类型 https://github.com/WeihanLi/DbTool/releases/tag/1.0.6

![image](https://user-images.githubusercontent.com/7604648/59999201-ff5aa400-9693-11e9-85c0-252d56dcbc95.png)
