### ISSUE TITLE
hello, 关于MySQL的字段类类型

### ISSUE THREAD

**Issue by chenzhihuiyyl** [WeihanLi/DbTool#8]
hello; 
    在使用表格转换成MySQL时， 单精度及双精度的长度在生成语句之后，是错误的（为空）；也没有‘TEXT’类型；望采纳！！

**Comment by WeihanLi** [comment]
感谢反馈，因为主要用 SqlServer，所以可能 MySql 的支持不是特别完善，我会找时间看一下的，多谢

**Comment by WeihanLi** [comment]
考虑扩展起来不太方便，而且 mysql 与 sqlserver 就有一些不太一样的数据类型，如果以后增加别的数据库支持，类型可能更多，因此移除了模板的数据库类型限制

新的模板下载地址: https://github.com/WeihanLi/DbTool/raw/wfdev/src/DbTool/template.xlsx
