### ISSUE TITLE
设计器没有?

### ISSUE THREAD

**Issue by xingdem108** [WeihanLi/DbTool#9]
为什么没有找到设计器?是去除了?

**Comment by WeihanLi** [comment]
net core 3.0  winform 设计器需要自己装一个 vs 插件，插件下载地址：<https://aka.ms/winforms-designer>

**Comment by WeihanLi** [comment]
https://devblogs.microsoft.com/dotnet/introducing-net-core-windows-forms-designer-preview-1/

**Comment by xingdem108** [comment]
如图,为什么设计界面回出现红线~~~也编辑不了
![微信图片_20191104235828](https://user-images.githubusercontent.com/5073785/68135712-0efdc980-ff5f-11e9-8ff8-da3363406f90.png)
